  jellyfin:
    image: jellyfin/jellyfin:latest
    user: uid:gid
    container_name: jellyfin
    network_mode: 'host'
    environment:
      TZ: "Europe/Warsaw"
      JELLYFIN_PublishedServerUrl: <adres_twojego_serwera>
    volumes:
      - ./jellyfin/files/config:/config
      - ./jellyfin/files/cache:/cache
      - /jellyfin/files/custom_config/index.html:/jellyfin/jellyfin-web/index.html:ro
      - /jellyfin/files/custom_config/redirect.js:/jellyfin/jellyfin-web/redirect.js:ro
      - type: bind
        source: /jellyfin/movies
        target: /movies
      - type: bind
        source: /jellyfin/series
        target: /series
    restart: 'unless-stopped'
